development:
  sessions:
    default:
      database: obdo
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: obdo
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      # username:
      # password:
      database: obdo
      hosts:
        - localhost:27017
